plugins {
    id 'groovy'
    id 'java'
    id 'jacoco'
    id 'application'
}

repositories {
   mavenCentral()
}

group = 'me.ineson.monitorNbn'
version = '001'

dependencies {
    implementation 'org.apache.groovy:groovy'
    // jsoup HTML parser library @ https://jsoup.org/
    implementation 'org.jsoup:jsoup:1.23.1'
}

application {
    mainClass = 'CheckModem'
}
