plugins {
  id 'java-library'
}

dependencies {
//    api "org.mongodb:mongo-java-driver:${mongodbVersion}"
    //implementation 'org.mongodb:mongo-java-driver:${mongodbVersion}'
//    implementation 'org.mongodb:mongodb-driver-sync:4.6.1'
    api "org.mongodb:mongodb-driver-sync:${mongodbVersion}"
    api 'org.apache.commons:commons-collections4:4.6.0'

    implementation "org.springframework.boot:spring-boot-starter-data-mongodb:${springBootVersion}"

    testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo:3.5.3'
    //testImplementation 'org.springframework:spring-context:5.2.6.RELEASE'
    testImplementation( "org.springframework.boot:spring-boot-starter-test:${springBootVersion}")
}
