plugins {
    id 'application'
}

dependencies {
    implementation project(':shared')   
	implementation "org.mongodb:mongodb-driver-sync:${mongodbVersion}"
	
    implementation 'org.apache.groovy:groovy'
    implementation 'commons-cli:commons-cli:1.11.0'
}

application {
    mainClass = 'me.ineson.monitorNbn.dataLoader.DataLoader'
}

